cluster.name: dingo_demo
cluster.coordinator.name: coordinator-resource
cluster.coordinator.tag: coordinator-tag
cluster.coordinator.replicas: 3
cluster.coordinator.partitions: 1

instance.host: executor
zookeeper.servers: zookeeper:2181

controller.name: dingo_controller
controller.mode: STANDALONE

server.coordinator.port: 19181
server.executor.port: 19191

default.replicas: 3
default.partitions: 3
data.dir: /opt/dingo/data
