---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  coordinator:
    image: ghcr.io/dingodb/dingo-ubuntu:main
    links: 
      - zookeeper:zookeeper
    hostname: coordinator
    container_name: coordinator
    depends_on:
      - zookeeper
    ports:
      - '19181:19181'
    environment:
       DINGO_ROLE: coordinator

  executor:
    image: ghcr.io/dingodb/dingo-ubuntu:main
    links: 
      - zookeeper:zookeeper
      - coordinator:coordinator
    hostname: executor
    container_name: executor
    depends_on:
      - coordinator
      - zookeeper
    ports:
      - '19191:19191'
    environment:
       DINGO_ROLE: executor
       CONFLUENT_ZK_ADDR: 'zookeeper:2181'
       DINGO_CLUSTER_NAME: dingo_1
       DINGO_INSTANCE_NAME: instance

volumes:
  minio_data:
    driver: local
