cluster.name: dingo_zhengjy
cluster.coordinator.name: coordinator-resource
cluster.coordinator.tag: coordinator-tag
cluster.coordinator.replicas: 3
cluster.coordinator.partitions: 1

instance.host: 192.168.6.190
zookeeper.servers: 172.20.3.83:2181

controller.name: dingo_controller
controller.mode: STANDALONE

server.coordinator.port: 19181
server.executor.port: 19191

default.replicas: 3
default.partitions: 3
data.dir: /root/work/dingo/data

SRCBUCKET_BUCKET: test
SRCBUCKET_PREFIX: test
SRCBUCKET_OBJECT: test
SRCBUCKET_REGION: ""
DESTBUCKET_BUCKET: test
DESTBUCKET_PREFIX: test
DESTBUCKET_OBJECT: test
DESTBUCKET_REGION: ""
ENDPOINTADDR: 172.20.3.18:9000
BOOTSTRAP_SERVER: 172.20.3.83:9092

#active: REPLICA
